### ISSUE TITLE
`Invalid memory address or nil pointer dereference` when tyring to destroy stack

### ISSUE THREAD

**Issue by Herklos** [okteto/destroy-stack#8]
Hi,

Thanks for your awesome work on Okteto github actions.

When I tried to destroy a stack using `okteto stack destroy` from the github action `destroy-stack` I got a `panic: runtime error: invalid memory address or nil pointer dereference` [here](https://github.com/Drakkar-Software/OctoBot-Demo/runs/3478289830?check_suite_focus=true#step:7:8).
Can you help me? Is it an issue with the Okteto destroy stack action?

**Comment by rberrelleza** [comment]
@Herklos we're looking into it. 

Here are the error logs, in case the github action goes away:

```
running: okteto stack destroy --namespace octobot-drakkarsoftware --name demo on /github/workspace
2021-08-31T22:31:17.5391134Z running: okteto stack destroy --namespace octobot-drakkarsoftware --name demo on /github/workspace
2021-08-31T22:31:17.6176730Z panic: runtime error: invalid memory address or nil pointer dereference
2021-08-31T22:31:17.6177556Z [signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x14c8ae5]
2021-08-31T22:31:17.6177997Z 
2021-08-31T22:31:17.6178414Z goroutine 1 [running]:
2021-08-31T22:31:17.6180015Z k8s.io/client-go/kubernetes.(*Clientset).CoreV1(0x0, 0x0, 0x24)
2021-08-31T22:31:17.6181040Z 	k8s.io/client-go@v0.20.1/kubernetes/clientset.go:270 +0x5
2021-08-31T22:31:17.6181950Z github.com/okteto/okteto/pkg/k8s/configmaps.Get(0x2e16b20, 0xc000050068, 0xc00117a120, 0xb, 0x7ffc597cc2e1, 0x17, 0x2e647c0, 0x0, 0xcf00000000000024, 0xc0002c3d40, ...)
2021-08-31T22:31:17.6183020Z 	github.com/okteto/okteto/pkg/k8s/configmaps/crud.go:16 +0x3e
2021-08-31T22:31:17.6183884Z github.com/okteto/okteto/pkg/k8s/configmaps.Deploy(0x2e16b20, 0xc000050068, 0xc00113b680, 0x7ffc597cc2e1, 0x17, 0x0, 0x1a, 0xc00009e600)
2021-08-31T22:31:17.6190346Z 	github.com/okteto/okteto/pkg/k8s/configmaps/crud.go:41 +0x8c
2021-08-31T22:31:17.6191367Z github.com/okteto/okteto/pkg/cmd/stack.Destroy(0x2e16b20, 0xc000050068, 0xc00092a870, 0x0, 0x6fc23ac00, 0x0, 0x0)
2021-08-31T22:31:17.6192132Z 	github.com/okteto/okteto/pkg/cmd/stack/destroy.go:54 +0x283
2021-08-31T22:31:17.6192864Z github.com/okteto/okteto/cmd/stack.Destroy.func1(0xc001152000, 0xc000737bc0, 0x0, 0x4, 0x0, 0x0)
2021-08-31T22:31:17.6193618Z 	github.com/okteto/okteto/cmd/stack/destroy.go:55 +0x21d
2021-08-31T22:31:17.6194323Z github.com/spf13/cobra.(*Command).execute(0xc001152000, 0xc000737b80, 0x4, 0x4, 0xc001152000, 0xc000737b80)
2021-08-31T22:31:17.6198372Z 	github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
2021-08-31T22:31:17.6199486Z github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f9b80, 0xc000ebd560, 0xc000edfe50, 0xe7ce0a)
2021-08-31T22:31:17.6200236Z 	github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
2021-08-31T22:31:17.6200814Z github.com/spf13/cobra.(*Command).Execute(...)
2021-08-31T22:31:17.6201397Z 	github.com/spf13/cobra@v1.1.1/command.go:895
2021-08-31T22:31:17.6202334Z github.com/okteto/okteto/cmd/utils.RunWithRetry(0xc000edff58, 0xc000edff48, 0x1)
2021-08-31T22:31:17.6203064Z 	github.com/okteto/okteto/cmd/utils/retry.go:27 +0x3c
2021-08-31T22:31:17.6203546Z main.main()
2021-08-31T22:31:17.6206557Z 	github.com/okteto/okteto/main.go:105 +0x904
```

**Comment by rberrelleza** [comment]
@Herklos we updated the version of `okteto` on the action, could you rerun your action from master to see if reproduces?

**Comment by Herklos** [comment]
Thanks @rberrelleza but it seems to keep failing : https://github.com/Drakkar-Software/OctoBot-Demo/runs/3489723726

**Comment by rberrelleza** [comment]
thanks for checking, we're looking at it.

**Comment by jLopezbarb** [comment]
The error occurs because the kubeconfig file is not configured. To configure it you can add the namespace action before deploying/destroying the stack. Another option would be to deploy the stack using the pipeline action.
It will return a user friendly error on the next release.

**Comment by Herklos** [comment]
Thanks for your help @rberrelleza and @jLopezbarb
